### ISSUE TITLE
Promoting our Project proposal task

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#104]
**Instructions**

- Create Clear Voice over for Animated Infographic Video to Post on Daily Social Media for Content and stories

- Use your Native language

- Make sure the Voice Over is with no other noise distractions and less than 60 seconds

- Always make Voice over ideas related to thenewboston

- You can reach out to Ms.ChrishaPh to connect with Animated Infographic Video Maker and start building a Team.

- Show us your  best creative Voice Over Ideas

**Comment by mrbusysky** [comment]
https://youtu.be/x4OAXaLUKxk
https://youtu.be/WuvrSgIFuws

fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337
