### ISSUE TITLE
Promote thenewboston Gifs

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#107]
**Instructions**

- Create Gifs to Post on Daily Social Media for Content and stories

- Always make Gifs ideas related to thenewboston

- Make sure it is  less than 30 seconds

- Show us your  best creative Gifs Ideas

P.S You can Check MakeAGIF.com for Ideas

**Comment by mrbusysky** [comment]
![thenewboston](https://user-images.githubusercontent.com/58412572/101901788-6dd04200-3b66-11eb-8bb0-f3a6c63bf5c7.gif)
Account Number: fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by mrbusysky** [comment]
![red text](https://user-images.githubusercontent.com/58412572/101902572-bdfbd400-3b67-11eb-96b9-280a85acd2dd.gif)

Account Number: fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by cyber41** [comment]
![rama_thenewboston](https://user-images.githubusercontent.com/17829082/105040144-8b9c9b00-5a72-11eb-835d-f2e047d22b0e.gif)




Account Number: 1c7e1f6ff735ccb06d8982cabff8f710d08f5980db820ab892fe21cdb1bab003
