### ISSUE TITLE
YouTube channel banner

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#109]
Looking for a new YouTube channel banner for thenewboston. The one I have there now was made for the Hello World video. Only the "TEXT AND LOGO SAFE AREA" section in the included template appears on desktop.

- https://www.youtube.com/user/thenewboston
- https://support.google.com/youtube/answer/2972003?hl=en

![f2e7893925d47e6a8783d55265fb645c](https://user-images.githubusercontent.com/8547538/101860647-21afde00-3b23-11eb-8612-f05654cbeaef.png)

## Current

![banner-image-new](https://user-images.githubusercontent.com/8547538/101943706-70e82400-3ba0-11eb-87b1-9a77b07f1ced.png)

![screencapture-youtube-user-thenewboston-2020-12-11-11_01_38](https://user-images.githubusercontent.com/8547538/101943634-4ac28400-3ba0-11eb-94ea-f101bbc606bd.png)

**Comment by manishram** [comment]
Not sure if this satisfies the need but I gave it a try.
**1. With Red Background**

![Open-source community for creators (7)](https://user-images.githubusercontent.com/22790904/101990127-e2bc8c80-3cca-11eb-91c3-fea76554359f.png)



**2. With Dark Blue Background**

![Open-source community for creators (8)](https://user-images.githubusercontent.com/22790904/101990136-fe279780-3cca-11eb-8a3e-67dda6bcea8e.png)

**Comment by buckyroberts** [comment]
@manishram What do you think https://www.youtube.com/user/thenewboston ?

**Comment by manishram** [comment]
Ooo sweet @buckyroberts :grin:

**Comment by tawanike** [comment]
@manishram Please share your account number for payments.

**Comment by manishram** [comment]
@tawanike 
Account:
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by tawanike** [comment]
Paid
