### ISSUE TITLE
Add YouTube videos to Website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#112]
Create a section on the website where we can add playlist https://www.youtube.com/user/thenewboston/playlists?view=1&sort=dd&shelf_id=0 and also to watch the videos in that playlist. We should probably organize the playlist by categories too (programming, math, chemistry, etc...)

We can also consider adding other YouTubers videos as well. Maybe even have the community submit ideas? I'm sure there would be some blockchain or crypto related content we could find that our community would be interested in.

**Comment by tomijaga** [comment]
Can I be assigned this?

**Comment by kristykjlee** [comment]
> Can I be assigned this?

@tomijaga Yes, feel free to pick this up! Designing in Figma would be preferable.

**Comment by tomijaga** [comment]
https://www.figma.com/file/U98aZaqEcnTGxDKZERRsIM/Youtube-Playlists?node-id=0%3A1

I would like to here your thoughts on this

**Comment by MahadAdil** [comment]
[https://www.figma.com/file/eboX0O4Tdh0WaMYerCZ5Dc/Playlist-Section?node-id=1%3A291](url)
@buckyroberts, @kristykjlee how about this design?

**Comment by davidyapdy** [comment]
Love the structure. But please adhere to our style guide.

**Comment by MahadAdil** [comment]
@davidyapdy I am actually new so can you please give me an idea of the style guide?

**Comment by davidyapdy** [comment]
It's in de description in the repo under design system.
https://github.com/thenewboston-developers/Design#design-system

**Comment by tomijaga** [comment]
@davidyapdy I adjusted my design to reflect the style guide
Check it out.
https://www.figma.com/file/U98aZaqEcnTGxDKZERRsIM/Youtube-Playlists?node-id=631%3A0

**Comment by davidyapdy** [comment]
Hey,

Added my comment in the design. Not bad. Need some minor improvement.
@buckyroberts <https://github.com/buckyroberts> please take a look from a
content creator POV if you can.

**Comment by tomijaga** [comment]
@davidyapdy Hello, I'm done with the improvements. I put used an elevation effect on the playlist Items section and implemented scroll functionality during presentations

**Comment by jonmidas** [comment]
Hello, please can I be assigned to this
