### ISSUE TITLE
YouTube Spring Boot Video Thumbnails

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#116]
We have some new video tutorials being uploaded and would like custom YouTube thumbnails for them. The subject is "Spring Boot". Typically we just have 1 thumbnail template for the series and for each thumbnail we just update the title. Some examples are shown below. Titles are:

- Introduction
- Hello World
- Project Structure
- Data Layer
- Data Source
- Service Layer

Also, if you include the PSD file as well then any designer in the future can create additional thumbnails (since we will be uploading more videos to the series soon).

Thumbnail image size and resolution - https://support.google.com/youtube/answer/72431?hl=en

<img width="1145" alt="Screen Shot 2021-01-05 at 3 32 45 PM" src="https://user-images.githubusercontent.com/8547538/103711124-954eda80-4f6b-11eb-9f1b-f4774e4664d7.png">
<img width="662" alt="Screen Shot 2021-01-05 at 3 33 00 PM" src="https://user-images.githubusercontent.com/8547538/103711129-96800780-4f6b-11eb-9a6f-d9d2d155a35d.png">

**Comment by dhakal0kushal** [comment]
![BIGREKO MOUSE_ Getting Over It #2 (1)](https://user-images.githubusercontent.com/55182298/103755288-b2e87680-5035-11eb-91d5-274246745b95.png)
Will share the editing link if it gets approved :) 
Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by mollykn** [comment]
![Untitled_Artwork](https://user-images.githubusercontent.com/30331122/103989303-9b8fb300-5133-11eb-9ef2-5c3ca9fd7891.jpg)
![Untitled_Artwork 2](https://user-images.githubusercontent.com/30331122/103989310-9f233a00-5133-11eb-9931-db2b15bbf50e.jpg)
Can include the PSD file. And will do "Hello World" thru "Service Layer" immediately after  picked.

Account Number: cdb4f7324dc63652d469357cba076cb614f1dc06ba20d6152deab895bd42dea0

**Comment by buckyroberts** [comment]
I know this wasn't included in the description but after looking at these can we:
- include the Spring Boot logo/graphic so people recognize it faster when they are searching for videos
- include the tutorial number so people can find the next video easier
- leave out "thenewboston" (no need for thenewboston branding)

**Comment by nicocrozier** [comment]
#2 maybe a "cooler" bottom bar and add the new requirements mentioned above. #mollykn

**Comment by skybrandevs** [comment]
Hi, i would love to work on this, how do i join this project

**Comment by mollykn** [comment]
> #2 maybe a "cooler" bottom bar and add the new requirements mentioned above. #mollykn

Made some modifications to the original based off the feedback :) 

![Untitled_Artwork](https://user-images.githubusercontent.com/30331122/104111867-95144f00-528b-11eb-9c65-d223033e1916.jpg)

**Comment by mollykn** [comment]
![Untitled_Artwork 2](https://user-images.githubusercontent.com/30331122/104114235-209ad980-52a6-11eb-859d-0a89ed3df0fc.jpg)

[Iteration 3]

**Comment by dhakal0kushal** [comment]
I did my version :) 
![BIGREKO MOUSE_ Getting Over It #2 (1)](https://user-images.githubusercontent.com/55182298/104115350-9b133a00-5336-11eb-8d5d-95789b0d8701.png)

**Comment by nicocrozier** [comment]
@mollykn can you update with a "#1" instead of just "1" . ty

**Comment by mollykn** [comment]
Added "#" @nicocrozier 
![Untitled_Artwork](https://user-images.githubusercontent.com/30331122/104135755-0dcfe580-5336-11eb-97f4-fc6d20d5dc13.jpg)

Account Number: cdb4f7324dc63652d469357cba076cb614f1dc06ba20d6152deab895bd42dea0

**Comment by buckyroberts** [comment]
@dhakal0kushal @mollykn Can we get both PSD templates? We can use one for this series and the other one we will use the template for another series. We can pay for both. Thanks!

**Comment by buckyroberts** [comment]
@dhakal0kushal @mollykn Can we get both PSD templates? We can use one thumbnail for this series and the other as a template for another series. We will pay for both. Thanks!

**Comment by dhakal0kushal** [comment]
Hi @buckyroberts, who should I send the link to. I was using Canva to create the thumbnail so I'll send the link with edit permission.

**Comment by buckyroberts** [comment]
@dhakal0kushal You can send it to me on Slack

**Comment by mollykn** [comment]
@buckyroberts I will send over the PSD templates on slack

**Comment by cyber41** [comment]
![Thenewboston_tutorial_thumbs](https://user-images.githubusercontent.com/17829082/104824960-af3fc580-5867-11eb-99cb-c286d335f12c.jpg)
Account Number: 1c7e1f6ff735ccb06d8982cabff8f710d08f5980db820ab892fe21cdb1bab003

**Comment by gkgaurav31** [comment]
![Thumbnail](https://user-images.githubusercontent.com/9574170/104886682-25d7e280-5990-11eb-9324-ae943fd287ab.png)
