### ISSUE TITLE
Promote Project Proposal Animated Video

### ISSUE THREAD

**Issue by dhakal0kushal** [thenewboston-developers/Design#118]
https://youtu.be/x1nMxXjT5g8

Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by buckyroberts** [comment]
Nice!

**Comment by manishram** [comment]
Liked the video. @Chrisha1212 can we get this shared on thenewboston social media?
