### ISSUE TITLE
Server banner for  Discord server

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#121]
1. Upload an image that’s at least 960x540 pixels in a 16:9 aspect ratio. Have a 1920x1080 image handy? Upload that and we’ll automatically resize it for you.
2. Keep the top 48px of the image fairly simple and free of any busy imagery. This way the title of your server will be easy to read for your community.
3. Avoid uploading an image with a logo or text in it.
4. Use an image that represents your game or brand. Key art, stills of a character, or subtle background art works well here. Here’s an example:
https://support.discord.com/hc/en-us/articles/360028716472 (edited)

**Comment by dhakal0kushal** [comment]
I don't know how to design :P 
![Cream and Blue Wallpaper](https://user-images.githubusercontent.com/55182298/106702881-35eaf580-6611-11eb-9b29-83ea533e8648.png)
Concept: Rebuilding the economy. People in the pic are trying to stabilize the economy. Also, has thenewboston logo summoned that gives the feeling of "we" the community working hard to build the crypto. 
My Account Number: 22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by stweyel** [comment]
![TNB discord1](https://user-images.githubusercontent.com/25363181/107590517-93ca9f00-6c08-11eb-805b-a24ba16fea45.png)
![TNB discord2](https://user-images.githubusercontent.com/25363181/107590564-b0ff6d80-6c08-11eb-9fdf-5d86eb32a5f0.png)
![TNB discord3](https://user-images.githubusercontent.com/25363181/107590570-b52b8b00-6c08-11eb-99fc-c367d0572801.png)

**Comment by mrbusysky** [comment]
![3](https://user-images.githubusercontent.com/58412572/108269762-5348b500-7123-11eb-914a-c2412b4abd5a.png)
![2](https://user-images.githubusercontent.com/58412572/108269899-80956300-7123-11eb-9f9f-b388c7d740a9.png)

Account number: fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337

**Comment by Rajputusman** [comment]
![image](https://user-images.githubusercontent.com/65516140/108621199-0b8f9980-7453-11eb-8202-e7513df3b684.png)
@mrbusysky Can you move the logo and title(THENEWBOSTON) a little bit downwards it will look good?

**Comment by dhakal0kushal** [comment]
![Cream and Blue Wallpaper](https://user-images.githubusercontent.com/55182298/108624793-3a1b6d80-746f-11eb-9541-2059c0faf890.png)
![Cream and Blue Wallpaper (2)](https://user-images.githubusercontent.com/55182298/108624808-47385c80-746f-11eb-851f-a6db6ec20309.png)
