### ISSUE TITLE
Bulk Payment Tools

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#122]
<img width="555" alt="Screen Shot 2021-02-04 at 2 55 47 PM" src="https://user-images.githubusercontent.com/8547538/106965847-1d560a80-66f9-11eb-878e-75cebc1b579a.png">

**Comment by AbhayAysola** [comment]
Maybe store all the account numbers in an excel sheet with the names and team. Then a simple python program could be used to read the excel sheet and send the coins to each account number.

**Comment by tomijaga** [comment]
@buckyroberts @kristykjlee
Bulk Transaktion Tool Design
https://www.figma.com/file/QxBpdgpU6H9MHimEED0GAJ/Bulk-Transactions-Tool?node-id=0%3A1

Feel free to comment if you would like me to change anything

**Comment by tomijaga** [comment]
@kristykjlee Was this design approved? I haven't received any payments for this
