### ISSUE TITLE
Compares and contrasts TNB against major crypto

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#128]
(+ New) a topic that compares and contrasts TNB against major crypto. High level from say a trader’s POV (e.g. use cases, marketing stuff).

**Comment by denistsoi** [comment]
Does this ticket require content writing? (or is it simply design?)

**Comment by tomijaga** [comment]
Can i be assigned this.

**Comment by kristykjlee** [comment]
Ah, sorry guys, Hargobind who is a Blockchain Researcher from the team is assigned to this ticket.

**Comment by Yara1990** [comment]
[Comparison.docx](https://github.com/thenewboston-developers/Design/files/6024887/Comparison.docx)

**Comment by kristykjlee** [comment]
@Yara1990 This is perfect! Just sent you payment. Thanks Hargobind!
