### ISSUE TITLE
Spice up the "Important Notes" design

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#130]
Instead of my ugly "Important Notes" styling, Vyz suggested we go with a better looking design.

## Ugly
<img width="733" alt="Screen Shot 2021-02-09 at 9 34 00 PM" src="https://user-images.githubusercontent.com/8547538/107469482-a4064f80-6b1e-11eb-8fb7-71a0e248084f.png">

## Not so ugly
<img width="954" alt="Screen Shot 2021-02-09 at 9 33 42 PM" src="https://user-images.githubusercontent.com/8547538/107469480-a2d52280-6b1e-11eb-9807-70247586e5d4.png">

<img width="928" alt="Screen Shot 2021-02-09 at 9 35 37 PM" src="https://user-images.githubusercontent.com/8547538/107469542-c6986880-6b1e-11eb-9361-8e136e94e99c.png">

**Comment by kristykjlee** [comment]
[Important Notes.fig.zip](https://github.com/thenewboston-developers/Design/files/5993662/Important.Notes.fig.zip)
