### ISSUE TITLE
Add link to blog on website

### ISSUE THREAD

**Issue by SteveHedden** [thenewboston-developers/Design#132]
We need links to the blog (https://thenewboston.blog/) on both the top and bottom nav bars on the website.

**Comment by buckyroberts** [comment]
- Where in the top menu? (also need text and icons)
- Where in the footer?
- Open in new tab or same tab?

**Comment by kristykjlee** [comment]
Closing issue and opens new one to state it clean. https://github.com/thenewboston-developers/Website/issues/1283
