### ISSUE TITLE
Toggle to show fees

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#140]
On the backend we are now including a `fee` indicator to mark which transactions are Bank and PV fees. This is because when the user is viewing their transactions, they usually only want to see the "real" transactions and not the fees.

Something simple like this might work.

![Fees](https://user-images.githubusercontent.com/8547538/107860383-e4eab680-6df3-11eb-8845-7842483cc9e3.png)

**Comment by kristykjlee** [comment]
https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/My-Accounts?node-id=352%3A1909
