### ISSUE TITLE
Create post/meme that explain the human value of thenewboston (not technical) 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#144]

**Comment by Ayah206** [comment]
can I work on this?

**Comment by kristykjlee** [comment]
Hey, this task is available for anyone to pick up. You just need to post up the meme you created in the issue, post it on slack & discord, and then add your account number to get paid for it.

**Comment by Ayah206** [comment]
Okay, got that

**Comment by randiaz95** [comment]
Hi!

![download](https://user-images.githubusercontent.com/18183906/110737810-10e33700-81fc-11eb-92b4-2c7eff815ed8.png)

![download (1)](https://user-images.githubusercontent.com/18183906/110737815-16408180-81fc-11eb-98a1-52cbe970fe3c.png)

71533980484bd121939cbc799b89f380f3bfa40f9f4158315f7d9650f7c0e87e

**Comment by kristykjlee** [comment]
@randiaz95 Per community feedback, we're no longer supporting payments for memes.
