### ISSUE TITLE
Create a post/meme that help us get to know the community

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#145]

**Comment by Musabii** [comment]
could you expand on 'get to know the community'? how can a meme do that?

**Comment by kristykjlee** [comment]
@Musabii it could be a regular post or it could be a meme. We've have a lot of members throw out really awesome ideas previously such as asking the community through a post "Whats your crypto knowledge on a scale of 1-10" and we were able to figure out the communities crypto knowledge very quickly through that. So anything that helps engage the community and helps us understand them more would be awesome. Also you can feel free to come up with your own topics as well, open for suggestions.

**Comment by sun-jay** [comment]
Hi, personally, I saw a lot of community interest in the real world value of coins, so could I suggest a post like: "Have you traded coins with a friend for something in real life?" or "If you could assign a value in USD to coins what would you give it?" 

Account number 
c0cbf80f3dbac1d93da883d7ac6d818ae7346e7994c2e623ff3e0576b88a19bd

**Comment by Ayah206** [comment]
can I get assigned to this task?

**Comment by kristykjlee** [comment]
Hey guys, this task is available for anyone to pick up. You just need to post up the meme you created in the issue, post it on slack & discord, and then add your account number to get paid for it.

**Comment by Prawesh-MAGNETIC** [comment]
<img width="1191" alt="crypto" src="https://user-images.githubusercontent.com/71756108/111026347-bfab9100-840f-11eb-9da6-952b1f271d0e.png">

**Comment by Prawesh-MAGNETIC** [comment]
b343d70bdc4bf593513bb30788b3c96f9ba2b78850534298c13d640c47832ecd
TNBC A/c

**Comment by Prawesh-MAGNETIC** [comment]
![thenewboston](https://user-images.githubusercontent.com/71756108/111036852-619aa000-8447-11eb-9b67-aa5a8f88b76e.png)

**Comment by kristykjlee** [comment]
@Prawesh-MAGNETIC Per community feedback, we're no longer supporting payments for memes.
