### ISSUE TITLE
Design for Account Manager Updates 

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Design#157]
We need a design for updating the **Account Manager** from the account manager itself without visiting the thenewboston website.

**Comment by manishram** [comment]
https://www.figma.com/proto/NG6GszRm3qatWuX0oZ5bMw/Update-Account-Manager?node-id=52%3A4885&scaling=min-zoom

**Comment by manishram** [comment]
Wait for @kristykjlee approval before engineering the designs.

**Comment by AnasNadeem** [comment]
Hey buddy. Can you assign it to me. I will do this.

**Comment by manishram** [comment]
Hey @AnasNadeem this one is done.

**Comment by whimsyniche** [comment]
> 
> 
> Hey @AnasNadeem this one is done.

Since this card is done will it be moved to another list (column) e.g. the "Done" list?

@kristykjlee maybe knows.

Just curious as I'm looking at things I can help with.
