### ISSUE TITLE
Meme

### ISSUE THREAD

**Issue by adewolejosh** [thenewboston-developers/Design#159]
account number: 074373d18830363452ea5bb3b17ad348adbad66526dc3962ab048beb7945f8e9
![1](https://user-images.githubusercontent.com/39972589/110964457-80b80580-8353-11eb-9882-80202cba5e0e.png)

**Comment by adewolejosh** [comment]
account number: 074373d18830363452ea5bb3b17ad348adbad66526dc3962ab048beb7945f8e9

![2](https://user-images.githubusercontent.com/39972589/111030906-15c70700-8405-11eb-8067-256f7b585d92.png)

**Comment by kristykjlee** [comment]
@adewolejosh Per community feedback, we will no longer be supporting paying for memes.
