### ISSUE TITLE
Make a webpage design for thenewboston recruitment form

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Design#167]
You need to make a design to add **thenewboston recruitment form**, for the FE team. You can access this form, using the following path in thenewboston's drive:

thenewboston drive > Community Process > Recruitment Drive > thenewboston recruitment 

@kristykjlee we just need to update the previous design and add one button for the google form. If you need anything else let me know.

**Comment by kristykjlee** [comment]
@ma2b0043 Hey Muhammad, added the Apply button that takes the user to the Google Form on the job details page. 
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=593%3A0

**Comment by ma2b0043** [comment]
Great job! Closing this issue now
