### ISSUE TITLE
[Windows] After each transcation there is an extra entry of one transcation

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#20]
**Bug Description**
When user send points to friends then in transactions there is an extra entry

**Steps to Reproduce**
Go to My accounts >>Transaction

**Expected behavior**
Only that entry should be displayed.

**Actual behavior**
Extra one entry is displayed.

**Screenshots/Recordings**
https://recordit.co/s7alf6haoh

**OS and Browser**
OS: [Windows 7]

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

![Screen Shot 2020-11-16 at 9 38 11 PM](https://user-images.githubusercontent.com/68207101/99351422-65316800-2855-11eb-93a2-c4ac29227f7e.png)

**Comment by kristykjlee** [comment]
![Uploading Screen Shot 2020-11-16 at 9.38.11 PM.png…]()

**Comment by kristykjlee** [comment]
![Screen Shot 2020-11-16 at 9 38 11 PM](https://user-images.githubusercontent.com/68207101/99350802-10d9b880-2854-11eb-9092-d76da79f53d3.png)

**Comment by Ramin-RX7** [comment]
this is my suggestion: [Image](https://ibb.co/583m469)
(I'm saying this again because in the screenshot you couldn't click on it and see it)
