### ISSUE TITLE
[Desktop]Font size for text looks too small

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#21]
Url: https://thenewboston.com/leaderboard/All
![94422658-0fb9d280-01a5-11eb-85ea-79f7746b6407](https://user-images.githubusercontent.com/68207101/99352514-a165c800-2857-11eb-9d11-5aff7667d0e1.png)

**Comment by mersimoski** [comment]
Momentarily is 12px, i suggest increasing it to 14px
![image](https://user-images.githubusercontent.com/62712311/99676170-73ab9980-2a78-11eb-978f-8977f6293f8a.png)
