### ISSUE TITLE
Teams page update

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#23]
**How to onboard new users**
https://docs.google.com/document/d/1SrqfJciZU6Ws8Qptxy3heUQYoJiOwydy71z8ITtU7ak/edit

**How to onboard team leads**
https://docs.google.com/document/d/1WYufbnATv4VDIf2q7qnLxt0wKP0EM8VzKvnMM_X6NAw/edit

**How the product development process works** 
https://docs.google.com/document/d/1HQZZy4EpZ1FeEr82FNby142etpn-l7WvbnsI6_8X-Q8/edit

**How to set up payment boards**
https://docs.google.com/document/d/1ICu_g0KaLoCmvrLJjDwwswmrX4nGbXx8fe_VgL2bcgk/edit?usp=sharing

**Core Team Roles & Responsibilities**
https://docs.google.com/document/d/1vOEMAsYzl9cbyQNoFVUNf54sQZF4wHv1mjgoAENMCpU/edit?usp=sharing

**Comment by odetolataiwo** [comment]
@kristykjlee paid
