### ISSUE TITLE
As a user, I would like to be able to sell my goods to accumulate more TNB coins

### ISSUE THREAD

**Issue by davidyapdy** [thenewboston-developers/Design#24]
We are implementing a marketplace that allows seller to list goods for sale and buyer to buy goods using TNB coins.

All submission to sell needs to go through a moderation process to the founding team for approval.

If a buyer would like to buy goods, buyer needs to initiate a direct message with the buyer via the CTA in good's detail page. It should redirect buyer to start a direct message with the seller from Slack.

Good detail page should include good image, title, description, price, seller's name and a CTA for DM.

![image](https://user-images.githubusercontent.com/17293366/99628237-b8cbcd80-2a70-11eb-9c94-7109b5cc2655.png)

![image](https://user-images.githubusercontent.com/17293366/99628266-c6815300-2a70-11eb-9644-29a82ac75f73.png)

**Design Specs:** https://www.figma.com/file/RhA9xnfISRLlc50jcNTEpA/Marketplace?node-id=0%3A1
**Components:** Website
**Priority**: High

**Comment by odetolataiwo** [comment]
@kristykjlee paid
