### ISSUE TITLE
Design suggestion for the Leaderboard for mobile.

### ISSUE THREAD

**Issue by mersimoski** [thenewboston-developers/Design#25]
Personally I don't think its ok to have the popup for the account number since its still website and not an mobile app, feels lagy somehow on older devices.

![image](https://user-images.githubusercontent.com/62712311/99675610-b325b600-2a77-11eb-85ff-6d210ed70c11.png)

This is the design i think it would fit best in the website.

**Comment by kristykjlee** [comment]
We no longer have a leaderboard, so I will close this issue.
