### ISSUE TITLE
Transaction Time Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#35]
**Transaction Time** comparing our avg. transaction time (0.015 seconds) to a traditional bank transfer (3-5 business days).

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best **creative** Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by AbhayAysola** [comment]
![TNB-Transaction-Time](https://user-images.githubusercontent.com/67417765/99875065-abe6df80-2c12-11eb-954d-20473f1ac14f.png)

I've made this according to the specifications. Let me know if I need to make any changes.

**Comment by AbhayAysola** [comment]
![TNB-Transaction-Time](https://user-images.githubusercontent.com/67417765/99900060-d187ed80-2cd3-11eb-9b13-ffb55fa5507d.png)
Let me know if I should make any changes.
