### ISSUE TITLE
Coins Memes Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#42]
**Coins Memes** make creative funny memes using coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by YashovardhanSingh** [comment]
![meme](https://user-images.githubusercontent.com/63940326/99983301-b26f8580-2dd1-11eb-8570-9f653a40ae31.png)
Account No: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by kristykjlee** [comment]
@YashovardhanSingh Can you update TheNewBoston to thenewboston (all lowercase) ? After that, all is good to go and then I'll make your payment go through!

**Comment by YashovardhanSingh** [comment]
@kristykjlee OK

**Comment by YashovardhanSingh** [comment]
![meme](https://user-images.githubusercontent.com/63940326/100061868-b55f8a00-2e54-11eb-9a05-f23490138d51.png)

**Comment by kristykjlee** [comment]
@YashovardhanSingh Can you also use a white block? Same as how you did for the first one? The new pinkish block doesnt make the text stand out.

**Comment by YashovardhanSingh** [comment]
![meme](https://user-images.githubusercontent.com/63940326/100063322-112b1280-2e57-11eb-97a0-9e6e8b67b1c1.png)
@kristykjlee

**Comment by kristykjlee** [comment]
@YashovardhanSingh alright cool! Thanks :D Will inform the payments team to send you payments

**Comment by kristykjlee** [comment]
@odetolataiwo This is ready for payment. 

User: YashovardhanSingh
Account No: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
Will I get more reward, If I create more memes?

**Comment by Chrisha1212** [comment]
Congratulation @YashovardhanSingh

**Comment by odetolataiwo** [comment]
@kristykjlee  done

**Comment by FredrickXavier** [comment]
![BlockChain Currency](https://user-images.githubusercontent.com/74035322/100629173-ff61d780-334e-11eb-9deb-6fc10d75a9ed.jpg)

**Comment by YashovardhanSingh** [comment]
![meme](https://user-images.githubusercontent.com/63940326/100630647-d2162900-3350-11eb-97f6-71a98396c87e.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by dhakal0kushal** [comment]
![4mt7oi_480](https://user-images.githubusercontent.com/55182298/101124535-5e5d7000-361f-11eb-84dc-0696239b79a3.jpg)
Account Number: 
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by dhakal0kushal** [comment]
![4ovsd0](https://user-images.githubusercontent.com/55182298/101125438-58688e80-3621-11eb-8154-961a14aeac4e.jpg)
Account Number:
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by kristykjlee** [comment]
@FredrickXavier @YashovardhanSingh @dhakal0kushal

Hey guys! Thanks for the hilarious and awesome memes! I just created a separate ticket for each of you. Next time you guys make a meme, can you guys make your own separate tickets instead of all commenting on the same ticket? It will really help the payments team a lot! Thanks guys! :D 

Once again, I made separate tickets for you guys, you will receive your payments soon.

**Comment by FredrickXavier** [comment]
Thanks, @kristykjlee. Sure next time we will create a meme along with a separate ticket.
