### ISSUE TITLE
Yes to Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#46]
**Yes to Coins**  reasons why to use coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by Toledit** [comment]
![designTNB](https://user-images.githubusercontent.com/27518021/100530079-953a1d00-31fe-11eb-91a1-6926b4421e60.png)

I did the design and the model from scratch so it is fully customizable. Let me know your comments and suggestions you have. thank you.

**Comment by kristykjlee** [comment]
Hey @Toledit this is awesome work! My main comment is on the way thenewboston is spelled. We currently spell thenewboston to be all lowercased, so would you be able to change TheNewBoston to thenewboston so we retain brand consistency? 

Also out of curiosity, have you tried making the coin red?

**Comment by Toledit** [comment]
Here are couple of variaty integrating the red color. 

![designTNB Light](https://user-images.githubusercontent.com/27518021/100675411-f9ccb780-3377-11eb-96e5-62f0e8db0483.jpg)
![designTNB dark](https://user-images.githubusercontent.com/27518021/100675425-005b2f00-3378-11eb-9396-b91af6e6eb0a.jpg)

**Comment by kristykjlee** [comment]
@Toledit This is great!! Can you post your account number?

**Comment by Toledit** [comment]
Thanks! 

c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
