### ISSUE TITLE
Motivational Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#53]
**Motivational Coin** making motivational template using coins as wealth.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100314960-c8ea2c80-2fdd-11eb-8f24-b3b7a2b78d38.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
@kristykjlee Please Review

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100317225-051f8c00-2fe2-11eb-9a2c-687d5b6fb172.png)

**Comment by kristykjlee** [comment]
@YashovardhanSingh 

So couple of things in your design
1. The hierarchy of the text needs to be improved. The biggest thing I see is the icons, but the most important thing is the text. So we need to make the year & the text stand out more, not the icon.
2. Per other infographics, please use color from the color palette
3. There should be thenewboston logo for the year 2020 esp if every other year has a logo. For this infographic, we can reduce the size of thenewboston logo at the top add the logo itself to the year 2020.

**Comment by YashovardhanSingh** [comment]
![moti](https://user-images.githubusercontent.com/63940326/100430089-4b491e00-30bc-11eb-990f-54f32b2a6254.png)

**Comment by kristykjlee** [comment]
@YashovardhanSingh Are we still going to include the dates per each timeline? It would make sense to add them because it puts the statements into context.

**Comment by YashovardhanSingh** [comment]
@kristykjlee 
![image](https://user-images.githubusercontent.com/63940326/100533597-355a6b00-322c-11eb-9908-27a65a132e28.png)

**Comment by kristykjlee** [comment]
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6
