### ISSUE TITLE
Blockchain topic Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#55]
**Blockchain topics** make some topics about blockchain.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by DrSparky-2007** [comment]
Hello! I have made an infographic for blockchain. The first file shows how blockchain works. The second shows how blocks are connected. The third talks about the security of blockchain.
![blockchain_1](https://user-images.githubusercontent.com/56183042/100079756-109c7700-2e6b-11eb-8f36-18a8aa0340b4.png)
![blockchain_2](https://user-images.githubusercontent.com/56183042/100079760-11cda400-2e6b-11eb-85d2-3035b99c0d7d.png)
![blockchain_3](https://user-images.githubusercontent.com/56183042/100079763-12663a80-2e6b-11eb-8e68-836acfe4b5fd.png)
Account: `ae1e084c6f9475f9604d9cf8aba68b54d5b217fefbb17d5a2f57ebfcd833eeab`
Btw, idea for coin's name: "Thenewcrypto" or "Thenewcoin"

**Comment by odetolataiwo** [comment]
@kristykjlee paid
