### ISSUE TITLE
Cryptocurrency topic Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#56]
**Cryptocurrency topic** make some topic about cryptocurrency.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by Toledit** [comment]
![Untitled-1](https://user-images.githubusercontent.com/27518021/100529990-c36b2d00-31fd-11eb-8c57-f2e484686de6.png)

**Comment by Toledit** [comment]
![asd](https://user-images.githubusercontent.com/27518021/100530122-1691af80-31ff-11eb-98be-29f29219c4a6.png)

**Comment by kristykjlee** [comment]
@Toledit This is great!! Can you post your account number?

**Comment by Toledit** [comment]
Appreciated! my account number: c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
