### ISSUE TITLE
Coins Topic Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#57]
**Coins Topic** makes some topics about our coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by pabloqb2000** [comment]
Hi, i'm not sure if these is the way you want us to send you our designs, but here they are. Contact me if you want them in any other format or if you want to change anything. I can send you the .psd file if it helps.

![transaction_time_infographic](https://user-images.githubusercontent.com/65713950/100134937-3a649680-2e89-11eb-9898-98bcefe73ead.png)
![block_time_infographic](https://user-images.githubusercontent.com/65713950/100134933-39cc0000-2e89-11eb-83fc-3599784d514b.png)
![node_types_infographic](https://user-images.githubusercontent.com/65713950/100134936-3a649680-2e89-11eb-9ab1-4f210a5fc752.png)

My acc `612ac38fb5e78536ba5aee13bf6fadf272be6d6c6ca3e9f4ca812d6d7f2a73d8`

Thanks for everything in advance.

**Comment by Chrisha1212** [comment]
@pabloqb2000 looks good

**Comment by kristykjlee** [comment]
@pabloqb2000 Hi Pablo! 

Couple of notes:
- thenewboston should be in all lower case and not upper case
- thenewboston should not have a dropshadow on the text itself

Can you try using the logos we have in our assets page, so we keep brand consistency? https://thenewboston.com/assets

**Comment by pabloqb2000** [comment]
@kristykjlee Hi, here I have the new versions. If there is anything else you want me to change just let me know.
Also tell me if you want me to make any other design.

![transaction_time_infographic](https://user-images.githubusercontent.com/65713950/100270986-0b1d5a80-2f59-11eb-9ef6-f8444e547628.png)
![block_time_infographic](https://user-images.githubusercontent.com/65713950/100270989-0bb5f100-2f59-11eb-9051-d556408498ed.png)
![node_types_infographic](https://user-images.githubusercontent.com/65713950/100270990-0c4e8780-2f59-11eb-8acc-a35e2abecc18.png)

**Comment by kristykjlee** [comment]
@pabloqb2000 Here you can use this white text logo for these designs to make the wordmark pop :) 
![512px](https://user-images.githubusercontent.com/68207101/100318467-f6e65700-2f72-11eb-86ec-bb02dc19b4a9.png)

Also do you think we should remove the logo on the bottom left? The logo is in so many places, its beginning to look really repetitive and unnecessary

**Comment by pabloqb2000** [comment]
@kristykjlee Sure, here you have the new versions. It's true, I might have overused the logo hahaha.

![node_types_infographic](https://user-images.githubusercontent.com/65713950/100341517-eff42e80-2fdc-11eb-831b-a7ed6103e99a.png)
![transaction_time_infographic](https://user-images.githubusercontent.com/65713950/100341521-f08cc500-2fdc-11eb-80d8-e8c063d74416.png)
![block_time_infographic](https://user-images.githubusercontent.com/65713950/100341522-f1255b80-2fdc-11eb-87c4-a286b1eacaba.png)

**Comment by kristykjlee** [comment]
@pabloqb2000 much better! Okay these are done.

@odetolataiwo Can you take care of this payment?
acc `612ac38fb5e78536ba5aee13bf6fadf272be6d6c6ca3e9f4ca812d6d7f2a73d8`

**Comment by kristykjlee** [comment]
@pabloqb2000 ah one last thing, we can only use the app on desktop for now, can you replace the 'Get this fast times on ANY DEVICE' portion with something else?

**Comment by pabloqb2000** [comment]
Sure @kristykjlee I've aslo changed the mobile icon in the "subtitle" as well.

![block_time_infographic](https://user-images.githubusercontent.com/65713950/100480423-81ed5b80-30f1-11eb-8c63-e9e26429116d.png)

**Comment by kristykjlee** [comment]
@pabloqb2000 Perfect! Thank you!

**Comment by kristykjlee** [comment]
acc 612ac38fb5e78536ba5aee13bf6fadf272be6d6c6ca3e9f4ca812d6d7f2a73d8
