### ISSUE TITLE
Earn Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#58]
**Earn Coins** showing how to earn coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100136621-46fce500-2eb1-11eb-95c9-0144f7b99bf2.png)

**Comment by eladcrock** [comment]
Hello, 
I'm working on  a draft in figma.  Are there any parameters, other than the style guide/color palette?

Many Thanks,
Dale Crockwell

**Comment by kristykjlee** [comment]
> Hello,
> I'm working on a draft in figma. Are there any parameters, other than the style guide/color palette?
> 
> Many Thanks,
> Dale Crockwell

Hey Dale,
You can use the style guide colors we have in the issue description & also heres another thing that will help with the process. This is a simple infographics template we've been using. The main thing is, please make sure it is legible through mobile as well. 
[Infographics.fig.zip](https://github.com/thenewboston-developers/Design/files/5706815/Infographics.fig.zip)
