### ISSUE TITLE
Coin Currency Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#59]
**Coin Currency** comparing the currency of our coins to other currencies.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by mrbusysky** [comment]
How does this differ from https://github.com/thenewboston-developers/Design/issues/61

**Comment by smazydev** [comment]
![Artboard 1](https://user-images.githubusercontent.com/43474082/101628965-6d3e8b00-3a42-11eb-9e3b-a4f7e9a6ecd9.png)
Account number: 52f7621a40de120ec863bbbcaef0a135a82c73589b2adefaba5f2efb0e17a60c

**Comment by kristykjlee** [comment]
> ![Artboard 1](https://user-images.githubusercontent.com/43474082/101628965-6d3e8b00-3a42-11eb-9e3b-a4f7e9a6ecd9.png)
> Account number: 52f7621a40de120ec863bbbcaef0a135a82c73589b2adefaba5f2efb0e17a60c

This is great content!! Also great design!! I'm putting this in the 'Done' column and out payments team will pay you for it!

**Comment by smazydev** [comment]
Hi, what's the payment ETA on this one?
Thank you for the kind words. :)

**Comment by tawanike** [comment]
Paid
