### ISSUE TITLE
Money to Currency Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#60]
**Money to currency** evolution of money to our coin currency.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by YashovardhanSingh** [comment]
@kristykjlee
![image](https://user-images.githubusercontent.com/63940326/100474718-48274f80-3107-11eb-89ce-98703e86c47a.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6
