### ISSUE TITLE
Facts about Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#61]
**Facts about Coins** truths about our coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100191888-f28c5080-2f16-11eb-9ce7-60ea6995f32a.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100193043-0fc21e80-2f19-11eb-96b1-ddd8e9508f69.png)

**Comment by kristykjlee** [comment]
@YashovardhanSingh Same comments has the previous infographics. 

1. Infographics needs to be 1080px by 1080px.
2. Make the body text bigger so it is viewable on mobile. 
3. Since this is all white text, you can use this thenewboston logo that has white text. 
4. I like the different colored background here, for all elements, can you select colors within our color palette? https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

![512px](https://user-images.githubusercontent.com/68207101/100316443-5fcbd000-2f6f-11eb-8b3b-62d37d753eb0.png)

**Comment by mrbusysky** [comment]
Is this still active?

**Comment by mrbusysky** [comment]
![black-top-text-1](https://user-images.githubusercontent.com/58412572/100955414-5a203e00-34cb-11eb-8ed1-6e9e237ac9b9.png)
![black-top-text-2](https://user-images.githubusercontent.com/58412572/100955417-5ab8d480-34cb-11eb-843a-11eff1bb5b29.png)
![black-top-text-3](https://user-images.githubusercontent.com/58412572/100955418-5ab8d480-34cb-11eb-89f3-a35af1ac7160.png)
![black-top-text-red](https://user-images.githubusercontent.com/58412572/100955420-5b516b00-34cb-11eb-9734-148c1414509e.png)
![black-top-text-red-2](https://user-images.githubusercontent.com/58412572/100955422-5b516b00-34cb-11eb-82e8-81d91dd4efab.png)
![black-top-text-red-3](https://user-images.githubusercontent.com/58412572/100955423-5b516b00-34cb-11eb-9ddb-ca71551284de.png)
![red-top-text-1](https://user-images.githubusercontent.com/58412572/100955424-5bea0180-34cb-11eb-8d2d-ed6425a0b332.png)
![red-top-text-2](https://user-images.githubusercontent.com/58412572/100955426-5bea0180-34cb-11eb-8929-1aa4363735df.png)
![red-top-text-3](https://user-images.githubusercontent.com/58412572/100955427-5bea0180-34cb-11eb-802f-09455d69c8ab.png)
![red-top-text-red](https://user-images.githubusercontent.com/58412572/100955429-5c829800-34cb-11eb-8617-46ea12c7fe4f.png)
![red-top-text-red-2](https://user-images.githubusercontent.com/58412572/100955430-5c829800-34cb-11eb-87eb-0924d3c707c5.png)
![red-top-text-red-3](https://user-images.githubusercontent.com/58412572/100955431-5d1b2e80-34cb-11eb-9319-1f1c26d81368.png)

**Comment by mrbusysky** [comment]
![thenewboston x2](https://user-images.githubusercontent.com/58412572/100959897-1bdb4c80-34d4-11eb-8e32-121b6376963d.gif)

**Comment by mrbusysky** [comment]
![image-1](https://user-images.githubusercontent.com/58412572/100960430-1af6ea80-34d5-11eb-9d23-12d8ab3e07b8.png)
![image-2](https://user-images.githubusercontent.com/58412572/100960433-1b8f8100-34d5-11eb-887c-8b4f18b81037.png)
![image-3](https://user-images.githubusercontent.com/58412572/100960434-1c281780-34d5-11eb-9fa1-108c9f78758d.png)
![image-4](https://user-images.githubusercontent.com/58412572/100960435-1c281780-34d5-11eb-8dec-8208e35fe9b8.png)
![image-5](https://user-images.githubusercontent.com/58412572/100960436-1cc0ae00-34d5-11eb-917f-66de48723e10.png)
![image-6](https://user-images.githubusercontent.com/58412572/100960437-1cc0ae00-34d5-11eb-96df-dab040786269.png)
![image-7](https://user-images.githubusercontent.com/58412572/100960438-1cc0ae00-34d5-11eb-8445-5ec3c6e7cda7.png)
![image-8](https://user-images.githubusercontent.com/58412572/100960439-1d594480-34d5-11eb-94c1-15f89c50d449.png)

**Comment by kristykjlee** [comment]
@mrbusysky looks great! can you provide your account number?

**Comment by mrbusysky** [comment]
My account number is fe06754d2dbf23509e975809e9023b620509c1e6618472f16c9659f59e940337
