### ISSUE TITLE
Spending Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#62]
**Spending coins** showing how to purchase stuff using our coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by smazydev** [comment]
![spendcoins-infographics](https://user-images.githubusercontent.com/43474082/100780207-43c2a580-342b-11eb-80db-815c756ea6aa.png)
Hi, This what I came up with. I'd be glad to change stuff, if its not up-to the mark.

**Comment by smazydev** [comment]
![spend-coins-infographics-red](https://user-images.githubusercontent.com/43474082/100782058-b2a0fe00-342d-11eb-9f28-6454571f488e.png)
Here's the red and white variant of it.
Account Number: 52f7621a40de120ec863bbbcaef0a135a82c73589b2adefaba5f2efb0e17a60c

**Comment by smazydev** [comment]
![spend-coins-infographics-red1](https://user-images.githubusercontent.com/43474082/100782689-98b3eb00-342e-11eb-852e-5391e6ba815d.png)
Here's the red and white version of it. I used the red on the logo. 
Account number: 52f7621a40de120ec863bbbcaef0a135a82c73589b2adefaba5f2efb0e17a60c
