### ISSUE TITLE
Trust Coins Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#63]
**Trust coins** reasons why non users and users should trust our coins.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by Niekon01** [comment]
![Trust Coin](https://user-images.githubusercontent.com/55133485/100717889-afcbec00-33e0-11eb-9af8-ee5599aba5c2.jpg)

**Comment by kristykjlee** [comment]
@Niekon01 Great work!!
