### ISSUE TITLE
Coins Mobile app Infographic

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#64]
**Coins Mobile app** showing how to use our mobile app.

**Instructions**

- Create Infographic to Post for Daily Social Media for Content and stories 
- Always make infographic ideas  related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas
- Use colors from our style guide color palette 
https://www.figma.com/file/ZLQBaMEsAQIdnfg5qtL384/Style-Guide?node-id=0%3A1

**Comment by Toledit** [comment]
![tnb coin](https://user-images.githubusercontent.com/27518021/100529969-8141eb80-31fd-11eb-8438-ce1c23be7543.png)

**Comment by kristykjlee** [comment]
@Toledit This is great!! Can you send your account number so we can pay you?

**Comment by Toledit** [comment]
my acount: 
c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
