### ISSUE TITLE
Reddit Banner

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#67]
**Request**
- Create a background banner as well as a mobile banner for our subreddit https://www.reddit.com/r/thenewboston/
- Background banner size: 4000 x 128 px
- Background banner size: 1600 x 480 px
- https://mods.reddithelp.com/hc/en-us/articles/360010112892-Banner

<img width="1239" alt="Screen Shot 2020-11-07 at 3 59 51 PM" src="https://user-images.githubusercontent.com/8547538/98453824-4ecb3400-2112-11eb-85a1-38c34ca9cb08.png">

**Comment by Godnoken** [comment]
> > Would love to take this challenge on! :)
> 
> Hey sorry @Godnoken this issue has already been worked on.

Oh, right. Where should I be looking to know what projects have been assigned to people?

**Comment by odetolataiwo** [comment]
@kristykjlee done

**Comment by kristykjlee** [comment]
> > > Would love to take this challenge on! :)
> > 
> > 
> > Hey sorry @Godnoken this issue has already been worked on.
> 
> Oh, right. Where should I be looking to know what projects have been assigned to people?

People should be stating on the issue itself that the ticket is assigned to them, but if they do not feel free to take it :) it looks like for this specific ticket, the person who finished it didnt comment on the ticket that it was assigned to them but finished it the moment you wanted to take the ticket.
