### ISSUE TITLE
thenewboston YouTube banner

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#68]
**Request:**
- New banner for https://www.youtube.com/user/thenewboston
- Resolution 2560 x 1440 pixels

You can use this as a template. The visible content needs to be within the "TEXT AND LOGO SAFE AREA".

![ta](https://user-images.githubusercontent.com/8547538/98453725-47eff180-2111-11eb-873a-6cc0ec92011c.png)

## Old one for reference
![thenewboston](https://user-images.githubusercontent.com/8547538/98453730-51795980-2111-11eb-8ec7-709b97c52b53.png)

## Current one for reference
![banner-image-new](https://user-images.githubusercontent.com/8547538/98453685-e6c81e00-2110-11eb-930f-dbe93b4c15a3.png)

**Comment by pabloqb2000** [comment]
Hi, I've made a banner for the channel, I don't know if this is what you are looking for.
Please let me know if you want to change anything.

![yt_banner](https://user-images.githubusercontent.com/65713950/100163363-c987a380-2eb5-11eb-93b6-0cf7c1ce24eb.jpg)

Here I include this image with some rulers for comparison for each screen size.

<img width="490" alt="yt_banner" src="https://user-images.githubusercontent.com/65713950/100163361-c8ef0d00-2eb5-11eb-83db-c60703e01c49.png">

Thanks in advance.
