### ISSUE TITLE
New README banner for thenewboston-python

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design#69]
**Request:**
- Updated README banner for https://github.com/thenewboston-developers/thenewboston-python 

The current one has our older blue logo with the arrow pointing up. Can we get one with the current red logo with the white arrow pointing right? As for the text on the right feel free to change it to however you want. We can also consider having the text under the logo. Whatever looks best. 

![b](https://user-images.githubusercontent.com/8547538/98453645-6e615d00-2110-11eb-8294-b162bcecb8ea.png)

**Comment by pabloqb2000** [comment]
Hi, I've made a new banner, check it out.
I've made two versions, with and without the python logo.
Let me know if you want to change anything

![python_banner](https://user-images.githubusercontent.com/65713950/100157416-cf2bbc00-2eaa-11eb-95fe-3ef87a18ad93.png)
![python_banner2](https://user-images.githubusercontent.com/65713950/100157419-cfc45280-2eaa-11eb-81d1-9e6ec3384fcb.png)
 Thanks in advace

**Comment by manishram** [comment]
This issue can be closed now.
