### ISSUE TITLE
Infographics on Project Proposals

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#70]
**Brief:**

- Create an infographic that will inform the community they can propose project ideas (https://thenewboston.com/project-proposals/overview). Project ideas must integrate with the TNB coin, user must formulate a team, and project ideas that are accepted will be funded with TNB coins. 

**Instructions:**
- Create Infographic to Post for Daily Social Media for Content and stories
- Always make infographic ideas related to thenewboston
- Making sure that your using Red and White as two main color for attraction
- Include logo for every infographic design
- 1080px by 1080px
- png or jpg
- Show us your the best creative Ideas

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100240268-626efb00-2f58-11eb-8687-9f2391e95477.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by kristykjlee** [comment]
Hey @YashovardhanSingh, this is a great start! One note, one of the criteria is to make the image 1080px by 1080px. This size will fit perfectly with social media posts.

**2 notes on content** 
1. For step 2 going onto 3, the only thing we're missing is saying something along the lines of your project proposals will be reviewed & then is great then accepted to then start earning coins.
2. One thing we should add is, the project idea has to integrate with the coin. Maybe we can say something like...propose an app idea that integrates the coin, get it reviewed, and then if accepted, start earning coins and be a part of building the future! Or something

**Comment by YashovardhanSingh** [comment]
@kristykjlee 
![image](https://user-images.githubusercontent.com/63940326/100311589-32663d00-2fd6-11eb-8daf-721e0902de6b.png)

**Comment by YashovardhanSingh** [comment]
@kristykjlee 
![image](https://user-images.githubusercontent.com/63940326/100315489-bb817200-2fde-11eb-9f9d-fafbd2a96818.png)

**Comment by YashovardhanSingh** [comment]
![image](https://user-images.githubusercontent.com/63940326/100317015-9a6e5080-2fe1-11eb-89e9-d889677efed7.png)

**Comment by YashovardhanSingh** [comment]
![project](https://user-images.githubusercontent.com/63940326/100319229-4a918880-2fe5-11eb-98d3-053efecc24ff.png)

**Comment by YashovardhanSingh** [comment]
@kristykjlee Is it done? I saw it on reddit.

**Comment by kristykjlee** [comment]
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
@odetolataiwo Please check this
