### ISSUE TITLE
Project Proposal Templates for social media

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#74]
We want to make people more aware of Project Proposals section, so we are going to start congratulating people for whenever they get a project approved or whenever they need to find additional team members, etc... And we are going to post them all over Reddit, LinkedIn, Twitter, Instagram. 

Create templates for:
- 1 template for congratulating user who got project approved
- 1 template for finding additional teammates for a project
- 1 template for congratulating and finding teammates (add both for this scenario)
- 1 template for congratulating multiple projects
- 1 templates for marketing first 20 approved will get 10,000 coins

Make sure the sizes are 1080px by 1080px (good for instagram)

**Comment by osaroadade** [comment]
Hey @kristykjlee, I think I'm done with this issue. I've created the last iteration you asked for.
