### ISSUE TITLE
HIFI - Coins Topic Infographic

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#77]
Create high fidelity infographics with the existing infographic content community members have made. 

**Instructions**
- Infographic must utilize existing design system. 
- Image must be 1080px by 1080px
- Image must be legible through mobile. 
- Image must be png or jpg

Here is an attachment of the infographic content the one community member has put together. 
![100134937-3a649680-2e89-11eb-9898-98bcefe73ead](https://user-images.githubusercontent.com/68207101/100841282-ed099b80-342b-11eb-854e-6493537b0cda.png)

@devanshgajjar Whenever your high-fidelity mock is finalized, attach the design onto the ticket and move the issue to the Done column on the Project board.

**Comment by devanshgajjar** [comment]
<img width="1080" alt="V1 3" src="https://user-images.githubusercontent.com/37979044/100842055-44485400-349e-11eb-82c9-abbe657c676f.png">
@kristykjlee

**Comment by odetolataiwo** [comment]
@devanshgajjar account number?

**Comment by devanshgajjar** [comment]
@odetolataiwo 

878191f1f66c58c53ae9179c3a7ea5ad7896f26f81d5201c3891f9ceb34fea72

**Comment by kristykjlee** [comment]
@devanshgajjar Hey devansh, check out your account. It looks like you already got paid 1,000. So for team members, you dont need to upload your account number because you are already on the payment roster.

**Comment by devanshgajjar** [comment]
@kristykjlee  Hello Kristy, we had a comment asking about the account number so that is why I put it here, anyway, I get it now and will take care about it.
