### ISSUE TITLE
HIFI - Motivational Coins Infographic

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#78]
Create high fidelity infographics with the existing infographic content community members have made. 

**Instructions**
- Infographic must utilize existing design system. 
- Image must be 1080px by 1080px
- Image must be legible through mobile. 
- Image must be png or jpg

Here is an attachment of the infographic content the one community member has put together. 
![100533597-355a6b00-322c-11eb-9908-27a65a132e28](https://user-images.githubusercontent.com/68207101/100841971-f3e4de00-342c-11eb-9141-a2b8fcbbb3ca.png)

@devanshgajjar Whenever your high-fidelity mock has went through review with @osaroadade and is finalized, attach the design onto the ticket and move the issue to the Done column on the Project board.

**Comment by devanshgajjar** [comment]
Here is an example of how it would look.
![image](https://user-images.githubusercontent.com/37979044/100966027-fc830480-3551-11eb-818f-a55c1087a2c8.png)

**Comment by devanshgajjar** [comment]
<img width="1080" alt="Motivational Coins Infographic #78" src="https://user-images.githubusercontent.com/37979044/100966179-55529d00-3552-11eb-8fb5-d5f914bc6d2e.png">
<img width="1080" alt="Motivational Coins Infographic #78 2" src="https://user-images.githubusercontent.com/37979044/100966192-5aafe780-3552-11eb-97f4-48f3ab083add.png">
<img width="1080" alt="Motivational Coins Infographic #78 3" src="https://user-images.githubusercontent.com/37979044/100966199-5f749b80-3552-11eb-96f5-c0a92412154f.png">
<img width="1080" alt="Motivational Coins Infographic #78 4" src="https://user-images.githubusercontent.com/37979044/100966209-61d6f580-3552-11eb-8a9e-477c8c13f19e.png">

@osaroadade

**Comment by osaroadade** [comment]
Looks good to me! But let's hear from @kristykjlee first. I believe she's the one with the final say.

**Comment by kristykjlee** [comment]
@devanshgajjar Looks great! All good to go.
