### ISSUE TITLE
HIFI - Infographics on Project Proposals

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#79]
Create high fidelity infographics with the existing infographic content community members have made. 

**Instructions**
- Infographic must utilize existing design system. 
- Image must be 1080px by 1080px
- Image must be legible through mobile. 
- Image must be png or jpg

Here is an attachment of the infographic content the one community member has put together. 
![100319229-4a918880-2fe5-11eb-98d3-053efecc24ff](https://user-images.githubusercontent.com/68207101/100842222-5b029280-342d-11eb-99f6-ac8cc9b7c10c.png)

@devanshgajjar Whenever your high-fidelity mock has went through review with Osaro and is finalized, attach the design onto the ticket and move the issue to the Done column on the Project board.

**Comment by devanshgajjar** [comment]
![image](https://user-images.githubusercontent.com/37979044/101136006-aafe7680-3632-11eb-9d01-7e51501d8f81.png)

**Comment by devanshgajjar** [comment]
<img width="1080" alt="Infographics on Project Proposals #79" src="https://user-images.githubusercontent.com/37979044/101136377-40016f80-3633-11eb-95ab-c155f927dbf8.png">
<img width="1080" alt="Infographics on Project Proposals #79 2" src="https://user-images.githubusercontent.com/37979044/101136408-4abc0480-3633-11eb-9a72-81bcbe643a74.png">
<img width="1080" alt="Infographics on Project Proposals #79 2-1" src="https://user-images.githubusercontent.com/37979044/101136413-4db6f500-3633-11eb-8fe9-bcb7398435b9.png">
