### ISSUE TITLE
HIFI - Money to Currency Infographic

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#80]
Create high fidelity infographics with the existing infographic content community members have made. 

**Instructions**
- Infographic must utilize existing design system. 
- Image must be 1080px by 1080px
- Image must be legible through mobile. 
- Image must be png or jpg

Here is an attachment of the infographic content the one community member has put together. 
![100474718-48274f80-3107-11eb-89ce-98703e86c47a](https://user-images.githubusercontent.com/68207101/100842291-78cff780-342d-11eb-8efc-df2f7c9fea34.png)

@devanshgajjar Whenever your high-fidelity mock has went through review with Osaro and is finalized, attach the design onto the ticket and move the issue to the Done column on the Project board.

**Comment by devanshgajjar** [comment]
![image](https://user-images.githubusercontent.com/37979044/101241040-cba0fc00-3718-11eb-8673-4403ccaf3693.png)

<img width="1080" alt="Money to Currency Infographic #80 2" src="https://user-images.githubusercontent.com/37979044/101240984-b1671e00-3718-11eb-8a97-15d213660658.png">
<img width="1080" alt="Money to Currency Infographic #80 3" src="https://user-images.githubusercontent.com/37979044/101240985-b330e180-3718-11eb-9a86-122fcee34923.png">
<img width="1080" alt="Money to Currency Infographic #80 4" src="https://user-images.githubusercontent.com/37979044/101240992-b3c97800-3718-11eb-97ee-7a40f6f253b4.png">
<img width="1080" alt="Money to Currency Infographic #80" src="https://user-images.githubusercontent.com/37979044/101241000-b4faa500-3718-11eb-801f-7b1c4e063546.png">
