### ISSUE TITLE
Coins Memes Infographic

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#85]
![100629173-ff61d780-334e-11eb-9deb-6fc10d75a9ed](https://user-images.githubusercontent.com/68207101/101137101-232d5380-35c3-11eb-9c1c-038b19015ac6.jpg)

For @FredrickXavier

Account Number :
dfddf07ec15cbf363ecb52eedd7133b70b3ec896b488460bcecaba63e8e36be5

**Comment by FredrickXavier** [comment]
Hi Team, I don't see the update of coins in my account, Have I done anything incorrectly?
