### ISSUE TITLE
Coins Memes Infographic

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#86]
![100630647-d2162900-3350-11eb-97f6-71a98396c87e](https://user-images.githubusercontent.com/68207101/101137361-9040e900-35c3-11eb-8ee2-7e8d92a20bfa.png)

For @YashovardhanSingh 

Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by YashovardhanSingh** [comment]
@kristykjlee Should I add more memes here or what?

**Comment by kristykjlee** [comment]
> @kristykjlee Should I add more memes here or what?

@YashovardhanSingh please make a new ticket for each one you create
