### ISSUE TITLE
Coin Memes

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Design#88]
@kristykjlee 
![meme](https://user-images.githubusercontent.com/63940326/101232639-b1472e00-36d8-11eb-9e5f-0ae7ba30f777.png)
Account Number: 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by kristykjlee** [comment]
@YashovardhanSingh Because the head is all red, it looks like thenewboston is causing a lot of headache. Is there another meme we can try?
