### ISSUE TITLE
Coins Memes Infographic (includes 3)

### ISSUE THREAD

**Issue by dhakal0kushal** [thenewboston-developers/Design#92]
![4ovu4g](https://user-images.githubusercontent.com/55182298/101273377-e462ed80-37bc-11eb-9bb5-a3bf20237b9c.jpg)
![4p0esp](https://user-images.githubusercontent.com/55182298/101273378-e62cb100-37bc-11eb-9f7e-049febfa2fd6.jpg)
![texttavla_del2_n168-01-frame](https://user-images.githubusercontent.com/55182298/101273379-e6c54780-37bc-11eb-9b0f-f78707bc294c.jpg)

Account Number:
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by Robel612** [comment]
Is this task still open?

**Comment by tawanike** [comment]
How much should be paid out for this work, there are 2 labels, 1000 and 2000.

**Comment by dhakal0kushal** [comment]
3000 coins I guess since it contains 3 memes each with the payout of 1000 coins :)

**Comment by bojan-ilijevski** [comment]
Can we still make memes and receive coins?

**Comment by kristykjlee** [comment]
@tawanike Hey tawanike! Just to clear confusion, @dhakal0kushal will be paid 3,000 for this ticket.
