### ISSUE TITLE
Logo designs for apparel/stickers

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design#94]

**Comment by Toledit** [comment]
Let me try to give a description of the sticker designs below.

1. This design represents the community collectively coming together to build a great thing, in this case, thenewboston network.
2, 3 & 4 are some unique designs promoting the brand (thenewboston and coin) in a cool way and let others search to draw attention. 5 is a bit cryptic design for our geeks out there. After all, we are dealing with cryptography at tnb🙂. It reads coin upside down 🙃.  with some variation.
Would love to hear your thoughts.

![Stickers](https://user-images.githubusercontent.com/27518021/101467430-5c631c00-3953-11eb-8368-80d44fa0cc50.jpg)

**Comment by Toledit** [comment]
![Stickers2](https://user-images.githubusercontent.com/27518021/101755400-dcb98680-3ae5-11eb-8ac3-3884749c6cf4.jpg)

**Comment by Toledit** [comment]
![StickerDesign](https://user-images.githubusercontent.com/27518021/102063132-b017ae80-3e06-11eb-98da-43c4093797ab.png)

**Comment by Toledit** [comment]
![StickerDesign2](https://user-images.githubusercontent.com/27518021/102064845-dd655c00-3e08-11eb-96d2-d90fa0bd86ed.png)

**Comment by Toledit** [comment]
![StickerDesignRed](https://user-images.githubusercontent.com/27518021/102065562-c7a46680-3e09-11eb-8fb0-b951ee3c159b.png)

**Comment by tawanike** [comment]
@Toledit Please share your account number for payments.

**Comment by Toledit** [comment]
my account number: c2c867ba352e754ab17d228871105edfcc1c0d33f32f57ff76823055041b417a
