### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Design#95]
We need a Contact Us page for our website.

The page is supposed to have a form with the following fields:
1. **First Name** and **Last Name** (Single Line Text Area)
2. **Email** (Single Line Text Area)
3. **Message** (Multiline Text Area)
4. **Send Message** Button

Below the above form page should have **Contact Information** Section
**Address**
**Email**

**Rough Sketch:** (Actual Layout can be different from this one as long as it looks good)
![contactus](https://user-images.githubusercontent.com/22790904/101469275-8d9b1680-396a-11eb-93f0-3ee2c717b64a.JPG)

**Comment by 54m50nd33n** [comment]
I got one for you

**Comment by olowudaniel1** [comment]
Can I get assigned to this?

**Comment by 54m50nd33n** [comment]
Sure

**Comment by ferasawadi** [comment]
ready to help

**Comment by Niekon01** [comment]
This issue has been assigned to me. Please look around and see if there are other works you can pick up. :)

**Comment by kristykjlee** [comment]
@Niekon01 Adarsh's designs

https://www.figma.com/file/Pecitr0a80MtisfG1BHppB/Contact-form-TNB?node-id=0%3A1
https://www.figma.com/file/0f3u9XtaRteofYR7zRwTxU/Contact-Page?node-id=0%3A1
