### ISSUE TITLE
Steps in Project Proposal

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Design#98]
**Instructions**

- Create an Infographic video to Post on Daily Social Media for Content and stories

- Always make Animated Infographic ideas related to thenewboston

- Make sure it is  less than 60 seconds

- You can put a  background music or you can reach Ms.ChrishaPh to connect you with Voice over script writers and start building a Team.

- Show us your  best creative Animated Infographic Video Ideas

**Comment by mrbusysky** [comment]
How does this differ from the other video for the project proposal?
